### ISSUE TITLE
Support Coral on NUC

### ISSUE THREAD

**Issue by alexandrepossebom** [roflcoopter/viseron#11]
I am trying to take a look at you software but I have a problema with NUC and Coral.

My config:

```

# See the README for the full list of configuration options.
cameras:
  - name: Backyard
    host: 192.168.1.50
    port: 554
    username: admin
    password: foobar
    path: /cam/realmonitor?channel=4&subtype=0
    motion_detection:
      interval: 1
      trigger: true
    object_detection:
      type: edgetpu
      interval: 1
      labels:
        - label: person
          confidence: 0.9
        - label: dog
          confidence: 0.9
        - label: car
          confidence: 0.9

# MQTT is optional
mqtt:
 broker: 192.168.1.100
 port: 1883
 username: mqtt
 password: foobar

logging:
  level: debug

```

I am giving this error:

```
Traceback (most recent call last):
  File "viseron.py", line 7, in <module>
    from lib.config import ViseronConfig
  File "/src/viseron/lib/config/__init__.py", line 118, in <module>
    VALIDATED_CONFIG = VISERON_CONFIG_SCHEMA(raw_config)
  File "/usr/local/lib/python3.6/dist-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.6/dist-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.6/dist-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['cameras'][0]['object_detection']['type']
```

I am running docker using this cmd line :
```
# docker run --rm -v /usr/share/hassio/share/viseron/recordings:/recordings -v /usr/share/hassio/share/viseron/config:/config -v /etc/localtime:/etc/localtime:ro -v /dev/bus/usb:/dev/bus/usb --privileged --name viseron --device /dev/dri roflcoopter/viseron:latest
```

Thank you in advanced.

**Comment by roflcoopter** [comment]
Thanks for showing interest in the project and also for the great issue report!

```type``` is not allowed to be specified under the ```object_detection``` block for a camera. It should be specified in the global domain, so your config needs to be like this:

```yaml
# See the README for the full list of configuration options.
cameras:
  - name: Backyard
    host: 192.168.1.50
    port: 554
    username: admin
    password: foobar
    path: /cam/realmonitor?channel=4&subtype=0
    motion_detection:
      interval: 1
      trigger: true
    object_detection:
      interval: 1
      labels:
        - label: person
          confidence: 0.9
        - label: dog
          confidence: 0.9
        - label: car
          confidence: 0.9

# MQTT is optional
mqtt:
 broker: 192.168.1.100
 port: 1883
 username: mqtt
 password: foobar

object_detection:
  type: edgetpu

logging:
  level: debug
```

Let me know if this works out for you

**Comment by alexandrepossebom** [comment]
Thank you @roflcoopter for your answer and sorry for my mistake.

Anyway I think x86 dockers machine doesn't have tensor flow.

Look my error now:

```
[2020-09-10 08:17:04] [lib.detector            ] [INFO    ] - Initializing detection thread
Traceback (most recent call last):
  File "viseron.py", line 163, in <module>
    main()
  File "viseron.py", line 43, in main
    detector = Detector(config)
  File "/src/viseron/lib/detector.py", line 20, in __init__
    from lib.edgetpu_detection import ObjectDetection
  File "/src/viseron/lib/edgetpu_detection.py", line 4, in <module>
    import tflite_runtime.interpreter as tflite
ModuleNotFoundError: No module named 'tflite_runtime'
```

**Comment by roflcoopter** [comment]
Ahh i see what the error is.
can you run this for me and see if it works?
```docker exec -it viseron bash pip3 install https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp37-cp37m-linux_x86_64.whl```

If it does i will add it to the image

**Comment by alexandrepossebom** [comment]
```
ERROR: tflite_runtime-2.1.0.post1-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform.
```

**Comment by roflcoopter** [comment]
Hmm what kind of machine are you running on?

**Comment by alexandrepossebom** [comment]
It's a Intel NUC i3

**Comment by roflcoopter** [comment]
Okey now i get it, the base ubuntu image contains python 3.6 so this would be the correct one.
```docker exec -it viseron bash pip3 install https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp36-cp36m-linux_x86_64.whl```

**Comment by alexandrepossebom** [comment]
Now it's works thank you!

but:
```
[2020-09-10 11:25:29] [lib.detector            ] [INFO    ] - Initializing detection thread
Traceback (most recent call last):
  File "viseron.py", line 163, in <module>
    main()
  File "viseron.py", line 43, in main
    detector = Detector(config)
  File "/src/viseron/lib/detector.py", line 24, in __init__
    label_path=self.config.object_detection.label_path,
  File "/src/viseron/lib/edgetpu_detection.py", line 13, in __init__
    self.labels = self.read_labels(label_path)
  File "/src/viseron/lib/edgetpu_detection.py", line 42, in read_labels
    labels[int(pair[0])] = pair[1].strip()
IndexError: list index out of range
```

**Comment by mario-tux** [comment]
it looks that the edgetpu labels file is not present in the docker image for NUC. I got a i3 NUC with Coral too.

**Comment by alexandrepossebom** [comment]
Thank you @roflcoopter now it's works.

**Comment by roflcoopter** [comment]
Great! Closing. Feel free to reopen this or a new issue if you are having trouble

**Comment by mario-tux** [comment]
> it looks that the edgetpu labels file is not present in the docker image for NUC. I got a i3 NUC with Coral too.

I was missing such file because I was using the `roflcoopter/viseron-vaapi:latest` image.

How should I make sure that ffmpeg is using vaapi in the decoding of the h264 image?

**Comment by roflcoopter** [comment]
I will fix so EdgeTPU is fully installed in the VAAPI image, along with models etc.
When you run the VAAPI image, it will automatically genereate the proper hwaccel arguments for ffmpeg.

What does your docker run command look like? And what processor do you use?

**Comment by mario-tux** [comment]
> What does your docker run command look like? 

I use docker compose (inside Portainer):
```
  viseron:
    container_name: viseron
    restart: unless-stopped
    network_mode: bridge
    privileged: true
    #image: roflcoopter/viseron-vaapi:latest
    image: roflcoopter/viseron:latest
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /etc/localtime:/etc/localtime:ro
      - /srv/docker/viseron/data:/config
      - /mnt/cctv/viseron:/recordings
```

> And what processor do you use?

My `/proc/cpuinfo` says `Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz`.

**Comment by roflcoopter** [comment]
if you turn on debug logging for the camera, what does the default ffmpeg command look like?

**Comment by mario-tux** [comment]
> if you turn on debug logging for the camera, what does the default ffmpeg command look like?

Indeed, it looks that the `viseron` container activate by default the vaapi con camera decoding:
```
[2020-09-12 09:59:27] [lib.camera.camera_1     ] [DEBUG   ] - FFMPEG decoder command: ffmpeg -hide_banner -loglevel panic -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts -stimeout 5000000 -use_wallclock_as_timestamps 1 -vsync 0 -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -rtsp_transport tcp -i rtsp://camera-1.lan:554/h264 -f rawvideo -pix_fmt nv12 pipe:1,
```

So the above `hwaccel_args` should not be necessary, right?

**Comment by roflcoopter** [comment]
No it shouldnt,  however it looks like you still have them in your config as ```-hwaccel_output_format yuv420p``` is not part of the default command
