### ISSUE TITLE
EdgeTPU on latest 1.8.0b5

### ISSUE THREAD

**Issue by JustMe0815** [roflcoopter/viseron#143]
I am getting an error when starting the container, but somehow it still seems to detect just fine.

`docker run --rm -v /mnt/2TB/surveillance/recordings:/recordings -v /mnt/2TB/surveillance/config:/config -v /etc/localtime:/etc/localtime:ro --name viseron --platform linux/arm/v7 roflcoopter/viseron:1.8.0b5`

```
[2021-04-07 09:48:18] [lib.detectors.edgetpu   ] [ERROR   ] - EdgeTPU not found. Detection will run on CPU
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tflite_runtime/interpreter.py", line 152, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/local/lib/python3.7/dist-packages/tflite_runtime/interpreter.py", line 111, in __init__
    raise ValueError(capture.message)
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/src/viseron/lib/detectors/edgetpu/__init__.py", line 28, in __init__
    tflite.load_delegate("libedgetpu.so.1", {"device": "usb"})
  File "/usr/local/lib/python3.7/dist-packages/tflite_runtime/interpreter.py", line 155, in load_delegate
    library, str(e)))
ValueError: Failed to load delegate from libedgetpu.so.1


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tflite_runtime/interpreter.py", line 152, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/local/lib/python3.7/dist-packages/tflite_runtime/interpreter.py", line 111, in __init__
    raise ValueError(capture.message)
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/src/viseron/lib/detectors/edgetpu/__init__.py", line 37, in __init__
    tflite.load_delegate("libedgetpu.so.1", {"device": "pci:0"})
  File "/usr/local/lib/python3.7/dist-packages/tflite_runtime/interpreter.py", line 155, in load_delegate
    library, str(e)))
ValueError: Failed to load delegate from libedgetpu.so.1


```

**Comment by roflcoopter** [comment]
That is the standard error message when no EdgeTPU can be found, its just printing the traceback for clarity but it isnt crashing.
In the dev branch i have changed that to a debug message instead to avoid confusion.
