### ISSUE TITLE
Object detection just stops after unspecified amount of time

### ISSUE THREAD

**Issue by JasonVarney** [roflcoopter/viseron#246]
Object detection has been working great but after a certain unspecified amount of time it just seems to die.

I can still see via nvidia-smi that something is still being processed...
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.38       Driver Version: 455.38       CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 2060    Off  | 00000000:0A:00.0 Off |                  N/A |
| 56%   62C    P2    85W / 170W |   3127MiB /  5932MiB |     44%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A    476166      C   python3                          1896MiB |
|    0   N/A  N/A    476228      C   servicearea                       245MiB |
|    0   N/A  N/A    476234      C   patio                             245MiB |
|    0   N/A  N/A    476241      C   garagedoor                        245MiB |
|    0   N/A  N/A    476250      C   poolarea                          245MiB |
|    0   N/A  N/A    476256      C   frontdoor                         245MiB |
+-----------------------------------------------------------------------------+
```

Only things I see in the logs that might be related...

This looks to be the likely culprit:
```
OpenCL error CL_MEM_OBJECT_ALLOCATION_FAILURE (-4) during call: clEnqueueNDRangeKernel('YUV2RGB_NVx', dims=2, globalsize=1280x648x1, localsize=NULL) sync=false
OpenCL error CL_MEM_OBJECT_ALLOCATION_FAILURE (-4) during call: clEnqueueNDRangeKernel('YUV2RGB_NVx', dims=2, globalsize=1280x648x1, localsize=NULL) sync=false
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.2) /tmp/opencv/modules/core/src/ocl.cpp:5911: error: (-220:Unknown error code -220) OpenCL error CL_MEM_OBJECT_ALLOCATION_FAILURE (-4) during call: clEnqueueWriteBuffer(q, handle=0x7ff2000c01c0, CL_TRUE, 0, sz=4478976, data=0x7ff2000c8600, 0, 0, 0) in function 'unmap'
```

This happens sporadically, think it's wifi interference, but usually doesn't cause a problem:
```
[h264 @ 0x55683a787740] top block unavailable for requested intra mode -1
[h264 @ 0x55683a787740] error while decoding MB 60 0, bytestream 99475
[h264 @ 0x55c1506c8880] left block unavailable for requested intra4x4 mode -1
[h264 @ 0x55c1506c8880] error while decoding MB 0 9, bytestream 91768
[h264 @ 0x55f7ceca2040] left block unavailable for requested intra4x4 mode -1
```

Also got a few of these but think it's related to the static mjpeg streams:
```
Exception in thread data_stream:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/src/viseron/data_stream.py", line 118, in consume_data
    self.static_subscriptions(data_item)
  File "/src/viseron/data_stream.py", line 99, in static_subscriptions
    self.run_callbacks(
  File "/src/viseron/data_stream.py", line 78, in run_callbacks
    for callback in callbacks.values():
RuntimeError: dictionary changed size during iteration
```

I've also noted that the Viseron MQTT topics disappear when above happens, apart from viseron/lwt=alive.

I'm going to try changing the YoloV4 model width & height to lower values, will try with 320x320, if that doesn't work an hourly crontab restart might be a workaround.

**Comment by roflcoopter** [comment]
> OpenCL error CL_MEM_OBJECT_ALLOCATION_FAILURE (-4) during call: clEnqueueNDRangeKernel('YUV2RGB_NVx', dims=2, globalsize=1280x648x1, localsize=NULL) sync=false
> OpenCL error CL_MEM_OBJECT_ALLOCATION_FAILURE (-4) during call: clEnqueueNDRangeKernel('YUV2RGB_NVx', dims=2, globalsize=1280x648x1, localsize=NULL) sync=false
> terminate called after throwing an instance of 'cv::Exception'
>   what():  OpenCV(4.5.2) /tmp/opencv/modules/core/src/ocl.cpp:5911: error: (-220:Unknown error code -220) OpenCL error CL_MEM_OBJECT_ALLOCATION_FAILURE (-4) during call: clEnqueueWriteBuffer(q, handle=0x7ff2000c01c0, CL_TRUE, 0, sz=4478976, data=0x7ff2000c8600, 0, 0, 0) in function 'unmap'

Does Viseron crash completely and exit or does it just silently stop processing?
Does it happen sporadically or when you do something? Can you reproduce it?
The error is thrown when your GPU runs out of memory. Viseron uses OpenCVs implementation of OpenCL to speed up image processing.
Since you are using an NVIDIA GPU it might run color plane conversion on the GPU, judging by the error message.
Can you show me the output of `clinfo` from inside the container?

> [h264 @ 0x55683a787740] top block unavailable for requested intra mode -1
[h264 @ 0x55683a787740] error while decoding MB 60 0, bytestream 99475
[h264 @ 0x55c1506c8880] left block unavailable for requested intra4x4 mode -1
[h264 @ 0x55c1506c8880] error while decoding MB 0 9, bytestream 91768
[h264 @ 0x55f7ceca2040] left block unavailable for requested intra4x4 mode -1

These can be safely ignored, its just warnings from FFmpeg and they should not affect anything.

>Exception in thread data_stream:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/src/viseron/data_stream.py", line 118, in consume_data
    self.static_subscriptions(data_item)
  File "/src/viseron/data_stream.py", line 99, in static_subscriptions
    self.run_callbacks(
  File "/src/viseron/data_stream.py", line 78, in run_callbacks
    for callback in callbacks.values():
RuntimeError: dictionary changed size during iteration

This is an unrelated bug, will fix.

**Comment by JasonVarney** [comment]
Hi, don't want to be premature and lead you on a wild-goose chase but thanks for the help.

It did seem to stop object detection silently, no crash or exit, actually with logging set to debug I can see Viseron happily checking at the set intervals continuously, that's the frustrating part.

There's also some Plex NVENC transcoding going on occasionally, that may be causing an OOM condition.

I've set the the YoloV4 Height & Width keys to 256x256 for now, nvidia-smi shows marginally less VRAM usage but far lower GPU utilisation >50% down to 27%, from 80-100W down to the 40W range. I'm guessing most of the VRAM usage is just the sheer frame-buffer size, 5x3Mpixel streams, will look into perhaps downgrading to 1080p streams. This setting is probably more sane and detections still seem to be relatively accurate.

There are a few confounding factors I need to look into, the cameras do an auto-reboot every night, aler9/rtsp-simple-server subscribes to them and in turn Viseron subscribes to the proxied streams from rtsp-simple-server, I've set a cronjob to restart Viseron after the connection between rtsp-simple-server and cameras is re-established.

Will keep an eye on things, try to reproduce, here is the output from clinfo you requested:

```
Number of platforms                               1
  Platform Name                                   NVIDIA CUDA
  Platform Vendor                                 NVIDIA Corporation
  Platform Version                                OpenCL 1.2 CUDA 11.1.110
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_device_uuid
  Platform Extensions function suffix             NV

  Platform Name                                   NVIDIA CUDA
Number of devices                                 1
  Device Name                                     GeForce RTX 2060
  Device Vendor                                   NVIDIA Corporation
  Device Vendor ID                                0x10de
  Device Version                                  OpenCL 1.2 CUDA
  Driver Version                                  455.38
  Device OpenCL C Version                         OpenCL C 1.2 
  Device Type                                     GPU
  Device Topology (NV)                            PCI-E, 0a:00.0
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               30
  Max clock frequency                             1680MHz
  Compute Capability (NV)                         7.5
  Device Partition                                (core)
    Max number of sub-devices                     1
    Supported partition types                     None
    Supported affinity domains                    (n/a)
  Max work item dimensions                        3
  Max work item sizes                             1024x1024x64
  Max work group size                             1024
  Preferred work group size multiple              32
  Warp size (NV)                                  32
  Preferred / native vector sizes                 
    char                                                 1 / 1       
    short                                                1 / 1       
    int                                                  1 / 1       
    long                                                 1 / 1       
    half                                                 0 / 0        (n/a)
    float                                                1 / 1       
    double                                               1 / 1        (cl_khr_fp64)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  Yes
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Address bits                                    64, Little-Endian
  Global memory size                              6220218368 (5.793GiB)
  Error Correction support                        No
  Max memory allocation                           1555054592 (1.448GiB)
  Unified memory for Host and Device              No
  Integrated memory (NV)                          No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       4096 bits (512 bytes)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        983040 (960KiB)
  Global Memory cache line size                   128 bytes
  Image support                                   Yes
    Max number of samplers per kernel             32
    Max size for 1D images from buffer            268435456 pixels
    Max 1D or 2D image array size                 2048 images
    Max 2D image size                             32768x32768 pixels
    Max 3D image size                             16384x16384x16384 pixels
    Max number of read image args                 256
    Max number of write image args                32
  Local memory type                               Local
  Local memory size                               49152 (48KiB)
  Registers per block (NV)                        65536
  Max number of constant args                     9
  Max constant buffer size                        65536 (64KiB)
  Max size of kernel argument                     4352 (4.25KiB)
  Queue properties                                
    Out-of-order execution                        Yes
    Profiling                                     Yes
  Prefer user sync for interop                    No
  Profiling timer resolution                      1000ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
    Kernel execution timeout (NV)                 No
  Concurrent copy and kernel execution (NV)       Yes
    Number of async copy engines                  3
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels                                (n/a)
  Device Extensions                               cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_device_uuid

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  NVIDIA CUDA
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [NV]
  clCreateContext(NULL, ...) [default]            Success [NV]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  Invalid device type for platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No platform

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.11
  ICD loader Profile                              OpenCL 2.1
  ```

**Comment by roflcoopter** [comment]
The YOLOv4 model is taking up the majority of the size in the memory, so changing the image size wont change much as you noticed.

Can you show me your docker run command?
I have two OpenCL devices available, one is my NVIDIA GPU and the other is a GPU integrated into the CPU.
If your CPU supports OpenCL then you could offload the images to that instead and you are less likely to run out of VRAM

**Comment by JasonVarney** [comment]
Ah yes, so changing model_width: and model_height:  is not passed to /detectors/models/darknet/yolov4.cfg, in my previous experiments for YOLOv3 changing the yolov3.cfg width and height would dramatically change VRAM usage during inference.

Perhaps I should run Viseron with the default YOLOv3 model by removing this from the config.yaml...
```
  model_path: /detectors/models/darknet/yolov4.weights
  model_config: /detectors/models/darknet/yolov4.cfg
  model_width: 256
  model_height: 256
```

Would downgrading the streams to 1080p help much with VRAM usage? I'd prefer to avoid that because I'd lose FOV due to the way the cameras bin the pixels. Could I resize the input feeds with some custom ffmpeg filter_args in the the config.yaml, would that even help?

My docker run command:
```
docker run -d --restart unless-stopped --name viseron  -e PUID=1000 -e PGID=1000 --tmpfs /tmp -v /opt/viseron/recordings:/recordings -v /opt/viseron:/config -v /etc/localtime:/etc/localtime:ro --runtime=nvidia -p 8888:8888 roflcoopter/amd64-cuda-viseron:1.9.0
```

Unfortunately running an AMD 3600X, no iGPU or OpenCL, even double checked with cat /proc/cpuinfo | grep -i opencl, nothing.

But so far with my current setup things seem to be running smoothly, cooler and with far less power consumption, >=8GB of VRAM would've been ideal though.


Thanks again for the time and effort.

**Comment by roflcoopter** [comment]
Sorry for the late reply, i am currently moving which is taking a lot of my time.

You might be able to force Viseron to not use OpenCL for image processing, object detection will still run on the GPU however.
You can try setting -e `VISERON_OPENCL_SUPPORTED=false` and see if it reduces the VRAM usage a little bit.

I am not sure if this works, i think my init scripts will overwrite this value, will look into it soon

**Comment by quick00198** [comment]
I am experiencing the same thing.  I am using the Nvidia docker.  Eventually the vram on GPU gets full and object detection stops working.

**Comment by roflcoopter** [comment]
@quick00198 do you get the same errors mentioned earlier from OpenCL?

**Comment by quick00198** [comment]
I stopped using the GPU container.  Switched over to RPI container with deepstack.
