### ISSUE TITLE
After recording an python error is reported

### ISSUE THREAD

**Issue by lyncker** [roflcoopter/viseron#250]
I am running Viseron on a Rasp3 with a Coral Stick added.... I configured the recorder and MQTT. After an dection event occured i get the following error in the log: 

`[2021-07-11 14:43:10] [INFO    ] [viseron.nvr.garage      ] - Stopping recording in: 9
[2021-07-11 14:43:11] [INFO    ] [viseron.nvr.garage      ] - Stopping recording in: 8
[2021-07-11 14:43:12] [INFO    ] [viseron.nvr.garage      ] - Stopping recording in: 7
[2021-07-11 14:43:13] [INFO    ] [viseron.nvr.garage      ] - Stopping recording in: 6
[2021-07-11 14:43:14] [INFO    ] [viseron.nvr.garage      ] - Stopping recording in: 5
[2021-07-11 14:43:15] [INFO    ] [viseron.nvr.garage      ] - Stopping recording in: 4
[2021-07-11 14:43:16] [INFO    ] [viseron.nvr.garage      ] - Stopping recording in: 3
[2021-07-11 14:43:17] [INFO    ] [viseron.nvr.garage      ] - Stopping recording in: 2
[2021-07-11 14:43:18] [INFO    ] [viseron.nvr.garage      ] - Stopping recording in: 1
[2021-07-11 14:43:19] [INFO    ] [viseron.nvr.garage      ] - Stopping recording in: 0
[2021-07-11 14:43:19] [INFO    ] [viseron.nvr.garage      ] - Pausing motion detector
[2021-07-11 14:43:19] [INFO    ] [viseron.recorder.garage ] - Stopping recorder
Exception in thread Thread-19:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/src/viseron/recorder.py", line 136, in concat_segments
    self._segmenter.concat_segments(
  File "/src/viseron/segments.py", line 215, in concat_segments
    temp_file = os.path.join("/tmp", file_name)
  File "/usr/lib/python3.8/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.8/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'`

here my recorder settings: 

`recorder:
  lookback: 10
  timeout: 10
  retain: 7
  filename_pattern: 'Garage_%H_%M_%S'
  thumbnail:
    save_to_disk: true
    send_to_mqtt: true`

**Comment by roflcoopter** [comment]
Will look into this ASAP.
I am in the process of moving tho so it might take a bit longer than usual

**Comment by lyncker** [comment]
maybe it has something to do with the location I am saving the files ?
I pointed the location in the compose yml file to a fat32 formated fileserver (NAS) volume ... the behave of viseron seems to be changing : If I use something like /home/user/viseron/rec für the recordings , viseron is always ( as configured and desired) saving a thumb picture next to the mp4 video. But using the fat32 volume only the video is beeing stored ....

**Comment by roflcoopter** [comment]
Closing this issue. If you still have issues, please try the latest version and see if the problem persists
