### ISSUE TITLE
how to debug "out of memory"

### ISSUE THREAD

**Issue by akohlsmith** [roflcoopter/viseron#26]
I just saw this exception when trying out the new (20200913) roflcoopter/verison-latest:

```
[2020-09-13 16:32:41] [lib.motion.cam04        ] [DEBUG   ] - Motion frames: 1, area: 1363.5
Exception in thread Thread-46:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/src/viseron/lib/camera.py", line 213, in capture_pipe
    pipe = self.pipe(stderr=True, single_frame=True)
  File "/src/viseron/lib/camera.py", line 190, in pipe
    bufsize=10 ** 8,
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1295, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory
```

I didn't change anything from the earlier version other than to make the default logging `info` and motion detection level `debug`.

**Comment by roflcoopter** [comment]
This is a tough one that i dont think i can help with.
This simply means your machine didnt have enough free memory, it could be Viseron or it could be some other process using up all your resources.

Viseron in itself uses quite a lot of memory, especially for the object detector but also the ```lookback``` feature. If you have a lot of cameras with high resolution and long ```lookback``` configured you will get even higher memory usage.

In the future i will try to transition to using ffmpeg segments instead of the storing frames in memory for the ```lookback```. I havent quite wrapped my head around how to do this yet tho

**Comment by akohlsmith** [comment]
Perhaps a data point for the books. Memory measured with `top` output, sorted by memory (`M` key):

* six 1080p cameras, motion_detect `interval: 0.2` (5fps), recorder `lookback: 15`: Resident memory is 9.8GB
* six 1080p cameras, motion_detect `interval: 0.5` (2fps), recorder `lookback: 15`: Resident memory is 7.1GB
* six 1080p cameras, motion_detect `interval: 1.0` (1fps), recorder `lookback: 15`: Resident memory is 6.2GB

**Comment by roflcoopter** [comment]
Okay that is very interesting. Off the top of my head, interval should have nothing to do with the memory usage.
I have to look into this more. Reopening.

I also think i need to prioritize the use of ffmpeg segments instead of storing frames in memory, because memory usage like this could be problematic.

**Comment by akohlsmith** [comment]
I was quite surprised by the memory usage myself, but I also understand that this is a pretty data-intense problem space. Lots of images hanging around, lots of decoding and resizing and filtering and god knows what else OpenCV has to have memory for so it can do its stuff.

As a comparison, the same cameras being monitored/motion-and-object detected/recorded by SecuritySpy at native camera speed (20fps, I actually reconfigured the cameras for a lower FPS due to this) seems to be about 1.5GB, but the VTDecoderXPC processes each take between 20MB and 200MB. It's definitely not easily comparable.

**Comment by roflcoopter** [comment]
Closing due to inactivity, feel free to reopen if the issue persists
