### ISSUE TITLE
First Pass @ Modularized Code  :: Repeating Message

### ISSUE THREAD

**Issue by gniknalu** [roflcoopter/viseron#319]
My first swipe at running the modularized code.  It starts off fine:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
************************ UID/GID *************************
User uid:    0
User gid:    0
************************** Done **************************
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-gid-video-device: executing...
[cont-init.d] 20-gid-video-device: exited 0.
[cont-init.d] 30-edgetpu-permission: executing...
************** Setting EdgeTPU permissions ***************
Coral Vendor IDs:
"1a6e",ATTRS{idProduct}=="089a"
"18d1",ATTRS{idProduct}=="9302"
No EdgeTPU USB device was found
************************** Done **************************
[cont-init.d] 30-edgetpu-permission: exited 0.
[cont-init.d] 40-set-env-vars: executing...
****** Checking for hardware acceleration platforms ******
OpenCL is available!
VA-API cannot be used
CUDA is available!
*********************** Done *****************************
[cont-init.d] 40-set-env-vars: exited 0.
[cont-init.d] 50-check-if-rpi: executing...
********** Checking if we are running on an RPi **********
Not running on any supported RPi
*********************** Done *****************************
[cont-init.d] 50-check-if-rpi: exited 0.
[cont-init.d] 55-check-if-jetson: executing...
****** Checking if we are running on a Jetson Board ******
Not running on any supported Jetson board
*********************** Done *****************************
[cont-init.d] 55-check-if-jetson: exited 0.
[cont-init.d] 60-ffmpeg-path: executing...
****************** Getting FFmpeg path *******************
FFmpeg path: /usr/local/bin/ffmpeg
*********************** Done *****************************
[cont-init.d] 60-ffmpeg-path: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-02-11 08:12:34] [INFO    ] [viseron                 ] - -------------------------------------------
[2022-02-11 08:12:34] [INFO    ] [viseron                 ] - Initializing...
```

**Then I get a repeating error:**

```
Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/src/viseron/__main__.py", line 26, in <module>
    init()
  File "/src/viseron/__main__.py", line 23, in init
    main()
  File "/src/viseron/__main__.py", line 9, in main
    viseron = setup_viseron()
  File "/src/viseron/__init__.py", line 95, in setup_viseron
    config = load_config()
  File "/src/viseron/config.py", line 47, in load_config
    raw_config = yaml.load(config_file, Loader=yaml.SafeLoader)
  File "/usr/local/lib/python3.8/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.8/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python3.8/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.8/dist-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "/config/config.yaml", line 3, column 5
expected <block end>, but found '<block mapping start>'
  in "/config/config.yaml", line 12, column 7
[2022-02-11 08:21:10] [INFO    ] [viseron                 ] - -------------------------------------------
[2022-02-11 08:21:10] [INFO    ] [viseron                 ] - Initializing...
Uncaught exception
```
And I'm running a minimal config file:

```
ffmpeg:
  camera:
    FrontEast2:
       name: Front East2
       host: !secret camera_ip_front_east2
       username: !secret camera_us_front_east2
       password: !secret camera_pw_front_east2
       path: /cam/realmonitor?channel=1&subtype=0&proto=Private3
       port: 80
       stream_format: mpeg4
       fps: 29
      recorder:
        idle_timeout: 1
        codec: h264
    FrontWest: #
       name: Front West
       host: !secret camera_ip_front_west
       username: !secret camera_us_front_west
       password: !secret camera_pw_front_west
       path: /Streaming/Channels/101?transportmode=unicast&profile=Profile_1
       port: 554
       stream_format: mpeg4
       fps: 25
      recorder:
        idle_timeout: 1
        codec: h264

darknet:
  object_detector:
    model_path: /detectors/models/darknet/yolov4-csp-x-swish.weights
    model_config: /detectors/models/darknet/yolov4-csp-x-swish.cfg
    cameras:
      FrontEast2:
        fps: 1
        scan_on_motion_only: false
        labels:
          - label: person
            confidence: 0.9
            trigger_recorder: true
      FrontWest:
        fps: 1
        labels:
          - label: person
            confidence: 0.9
            trigger_recorder: true
nvr:
  FrontEast2:
  FrontWest:

webserver:

mqtt:
  broker: !secret mqtt_host
  port: !secret mqtt_port
  username: !secret mqtt_us
  password: !secret mqtt_pw
  client_id: viseron
  home_assistant:

logger:
  default_level: debug
  logs:
    viseron.components.data_stream: info
    viseron.components.background_subtractor: info
    viseron.components.mog2: info
```

**A few things I don't yet grasp:** 
mog2 <--- Not sure what this is and how to configure it
darknet <-- How do I determine the paths for "model_path" and "model_config"
webserver <-- And how do I access it - is it running on port 80?

Thank you

**Comment by roflcoopter** [comment]
The `recorder` blocks are not indented correctly, missing one space, like this

```yaml
ffmpeg:
  camera:
    FrontEast2:
       name: Front East2
       host: !secret camera_ip_front_east2
       username: !secret camera_us_front_east2
       password: !secret camera_pw_front_east2
       path: /cam/realmonitor?channel=1&subtype=0&proto=Private3
       port: 80
       stream_format: mpeg4
       fps: 29
       recorder:
         idle_timeout: 1
         codec: h264
    FrontWest: #
       name: Front West
       host: !secret camera_ip_front_west
       username: !secret camera_us_front_west
       password: !secret camera_pw_front_west
       path: /Streaming/Channels/101?transportmode=unicast&profile=Profile_1
       port: 554
       stream_format: mpeg4
       fps: 25
       recorder:
         idle_timeout: 1
         codec: h264

darknet:
  object_detector:
    model_path: /detectors/models/darknet/yolov4-csp-x-swish.weights
    model_config: /detectors/models/darknet/yolov4-csp-x-swish.cfg
    cameras:
      FrontEast2:
        fps: 1
        scan_on_motion_only: false
        labels:
          - label: person
            confidence: 0.9
            trigger_recorder: true
      FrontWest:
        fps: 1
        labels:
          - label: person
            confidence: 0.9
            trigger_recorder: true
nvr:
  FrontEast2:
  FrontWest:

webserver:

mqtt:
  broker: !secret mqtt_host
  port: !secret mqtt_port
  username: !secret mqtt_us
  password: !secret mqtt_pw
  client_id: viseron
  home_assistant:

logger:
  default_level: debug
  logs:
    viseron.components.data_stream: info
    viseron.components.background_subtractor: info
    viseron.components.mog2: info
```



> mog2 <--- Not sure what this is and how to configure it

Thats a motion detector, the same as the old one that was specified with
```yaml
motion_detection:
  type: mog2
```

> darknet <-- How do I determine the paths for "model_path" and "model_config"

You can find all the models in the image by running 
```
docker exec -it viseron ls -al /detectors/models/darknet/
```

> webserver <-- And how do I access it - is it running on port 80?

The webserver runs on port 8888 by default, so you need to map it in your docker run command or docker-compose

**Comment by gniknalu** [comment]
That fixed those ones. Will open another to make it easier to track. Thank you!
