### ISSUE TITLE
modularized ::  line 352, in get_codec :: KeyError: 'hevc'

### ISSUE THREAD

**Issue by gniknalu** [roflcoopter/viseron#322]
Added another camera. The stream from the camera has the video Codec MPEG-H Part2/HVEC (H.265) with the audio Codec PCM ALAW

For the recorder I used `codec: h265`

I'm getting this error:
```
ERROR:root:Uncaught thread exception
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/src/viseron/components/ffmpeg/camera.py", line 232, in read_frames
    self.stream.start_pipe()
  File "/src/viseron/components/ffmpeg/stream.py", line 474, in start_pipe
    self._logger.debug(f"FFmpeg decoder command: {' '.join(self.build_command())}")
  File "/src/viseron/components/ffmpeg/stream.py", line 433, in build_command
    stream_input_command = self.stream_command(
  File "/src/viseron/components/ffmpeg/stream.py", line 370, in stream_command
    + self.get_codec(stream_config, stream_codec)
  File "/src/viseron/components/ffmpeg/stream.py", line 352, in get_codec
    return ["-c:v", codec_map[stream_codec]]
KeyError: 'hevc'
```
I removed `codec: h265` and still get the error.

Suggestions?

**Comment by roflcoopter** [comment]
can you paste your full config?

**Comment by gniknalu** [comment]
> can you paste your full config?

Full Config:

```
ffmpeg:
  camera: 
    FrontEast2: 
       name: Front East2
       host: !secret camera_ip_front_east2
       username: !secret camera_us_front_east2
       password: !secret camera_pw_front_east2
       path: /cam/realmonitor?channel=1&subtype=0&proto=Private3
       port: 80
       fps: 29
       recorder:
         idle_timeout: 1
         codec: h264
    FrontWest: 
       name: Front West
       host: !secret camera_ip_front_west
       username: !secret camera_us_front_west
       password: !secret camera_pw_front_west
       path: /Streaming/Channels/101?transportmode=unicast&profile=Profile_1
       port: 554
       fps: 25
       recorder:
         idle_timeout: 1
         codec: h264
    BackEast:
       name: Back East
       host: !secret camera_ip_back_east
       username: !secret camera_us_back_east
       password: !secret camera_pw_back_east
       path: /cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif/trackID=0
       port: 554
       fps: 29
       recorder:
         idle_timeout: 1
         codec: hevc_cuvid
         filename_pattern: '%Y-%m-%d-%H%M%S'
         lookback: 12
         retain: 90
         thumbnail:
           filename_pattern: '%Y-%m-%d-%H%M%S'

mog2:
  motion_detector:
    cameras:
      FrontEast2:
        fps: 2
      FrontWest:
        fps: 2
      BackEast:
        fps: 2

darknet:
  object_detector:
    model_path: /detectors/models/darknet/yolov4-csp-x-swish.weights
    model_config: /detectors/models/darknet/yolov4-csp-x-swish.cfg
    cameras:
      FrontEast2:
        fps: 2
        scan_on_motion_only: false
        labels:
          - label: person
            confidence: 0.9
            trigger_recorder: true
          - label: dog
            confidence: 0.8
            trigger_recorder: true
          - label: cat
            confidence: 0.8
            trigger_recorder: true
          - label: truck
            confidence: 0.8
            trigger_recorder: true
            require_motion: true
          - label: car
            confidence: 0.8
            trigger_recorder: true
            require_motion: true

      FrontWest:
        fps: 2
        labels:
          - label: person
            confidence: 0.9
            trigger_recorder: true
          - label: dog
            trigger_recorder: true
          - label: cat
            trigger_recorder: true
          - label: truck
            confidence: 0.8
            trigger_recorder: true
            require_motion: true
          - label: car
            confidence: 0.8
            trigger_recorder: true
            require_motion: true
      BackEast:
        fps: 2
        labels:
          - label: person
            confidence: 0.9
            trigger_recorder: true
          - label: dog
            trigger_recorder: true
          - label: cat
            trigger_recorder: true

background_subtractor:
  motion_detector:
    cameras:
      FrontEast2: 
        fps: 2
        mask:
          - coordinates:
              - x: 957
                y: 1515
              - x: 957
                y: 676
              - x: 1186
                y: 438
              - x: 2100
                y: 438
              - x: 2684
                y: 590
              - x: 2684
                y: 1
              - x: 1
                y: 1
              - x: 1
                y: 1515
      FrontWest: 
        fps: 2
        mask:
          - coordinates:
              - x: 294
                y: 0
              - x: 1920
                y: 0
              - x: 1920
                y: 206
              - x: 1651
                y: 136
              - x: 1454
                y: 150
              - x: 1120
                y: 114
              - x: 321
                y: 233
      BackEast: 
        fps: 2
        mask:
          - coordinates:
              - x: 1914
                y: 1
              - x: 320
                y: 1
              - x: 320
                y: 148
              - x: 872
                y: 33
              - x: 1914
                y: 174
        

nvr:
  FrontEast2: 
  FrontWest: 
  BackEast:
  
webserver:

mqtt:
  broker: !secret mqtt_host
  port: !secret mqtt_port
  username: !secret mqtt_us
  password: !secret mqtt_pw
  client_id: viseron
  home_assistant:

logger:
  default_level: debug
  logs:
    viseron.components.data_stream: info
    viseron.components.background_subtractor: info
    viseron.components.mog2: info
```

**Comment by gniknalu** [comment]
> lookback

The following was something I was experimenting with to try to fix it:
`codec: hevc_cuvid`

**Comment by roflcoopter** [comment]
what happens if you remove `codec`?

**Comment by gniknalu** [comment]
> what happens if you remove `codec`?

Just removed the line (which wasn't added until I saw the error). With it removed:

```
[2022-02-14 07:07:59] [INFO    ] [viseron.components      ] - Setting up domain motion_detector for component mog2
[2022-02-14 07:07:59] [INFO    ] [viseron.components      ] - Setting up domain object_detector for component darknet
[2022-02-14 07:08:00] [ERROR   ] [viseron.states          ] - Component mog2 does not generate unique entity IDs
[2022-02-14 07:08:00] [ERROR   ] [viseron.states          ] - Component background_subtractor does not generate unique entity IDs
[2022-02-14 07:08:05] [INFO    ] [viseron.components      ] - Setting up nvr
[2022-02-14 07:08:05] [ERROR   ] [viseron                 ] - Requested object detector BackEast has not been registered. Available object detectors are: ['FrontEast2', 'FrontWest']
[2022-02-14 07:08:05] [INFO    ] [viseron.components.nvr.BackEast] - Object detector is disabled
[2022-02-14 07:08:05] [INFO    ] [viseron                 ] - Initialization complete
ERROR:root:Uncaught thread exception
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/src/viseron/components/ffmpeg/camera.py", line 232, in read_frames
    self.stream.start_pipe()
  File "/src/viseron/components/ffmpeg/stream.py", line 474, in start_pipe
    self._logger.debug(f"FFmpeg decoder command: {' '.join(self.build_command())}")
  File "/src/viseron/components/ffmpeg/stream.py", line 433, in build_command
    stream_input_command = self.stream_command(
  File "/src/viseron/components/ffmpeg/stream.py", line 370, in stream_command
    + self.get_codec(stream_config, stream_codec)
  File "/src/viseron/components/ffmpeg/stream.py", line 352, in get_codec
    return ["-c:v", codec_map[stream_codec]]
KeyError: 'hevc'
```

**Comment by roflcoopter** [comment]
It's a bug in the new implementation, will fix soon.

But you should be able to work around it by putting `codec: hevc_cuvid` for the camera config (not the recorder)

**Comment by gniknalu** [comment]
> But you should be able to work around it by putting `codec: hevc_cuvid` for the camera config (not the recorder)

```
ERROR:root:Uncaught thread exception
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/src/viseron/components/ffmpeg/camera.py", line 232, in read_frames
    self.stream.start_pipe()
  File "/src/viseron/components/ffmpeg/stream.py", line 474, in start_pipe
    self._logger.debug(f"FFmpeg decoder command: {' '.join(self.build_command())}")
  File "/src/viseron/components/ffmpeg/stream.py", line 433, in build_command
    stream_input_command = self.stream_command(
  File "/src/viseron/components/ffmpeg/stream.py", line 368, in stream_command
    input_args
TypeError: can only concatenate list (not "str") to list
```
It didn't work. I'll wait for the update/fix. Thank you!

**Comment by roflcoopter** [comment]
Silly me, should work now (both with and without `codec`)

**Comment by roflcoopter** [comment]
Thats because the audio codec `pcm_alaw` is not supported in `mp4` container by ffmpeg.
This is nothing new to this release, what did your config look like for the previous versions of Viseron?
Did you specify `audio_codec` or `extension` there?

**Comment by gniknalu** [comment]
> Thats because the audio codec `pcm_alaw` is not supported in `mp4` container by ffmpeg. This is nothing new to this release, what did your config look like for the previous versions of Viseron? Did you specify `audio_codec` or `extension` there?

This is my old config for that camera:

```
  - name: "BackEast"
    host: !secret camera_ip_back_east
    port: !secret camera_port_back_east
    stream_format: rtsp
    username: !secret camera_us_back_east
    password: !secret camera_pw_back_east
    path: /cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif/trackID=0
    fps: 25
    mqtt_name: camera_back_east
    publish_image: true
    static_mjpeg_streams:
      stream_back_east:
        draw_objects: true
        draw_motion: true
        draw_zones: true
    motion_detection:
      interval: 1
      trigger_detector: false
      threshold: 15
      alpha: 0.6
      max_timeout: 300
    object_detection:
      interval: 1
```

**Comment by roflcoopter** [comment]
And for `recorder`?

**Comment by gniknalu** [comment]
> And for `recorder`?

```
recorder:
  extension: mkv
  filename_pattern: '%Y-%m-%d-%H%M%S'
  lookback: 12
  timeout: 12
  retain: 60
  thumbnail:
    filename_pattern: '%Y-%m-%d-%H%M%S'
    send_to_mqtt: true

```

**Comment by roflcoopter** [comment]
That explains it, you need to add `extension: mkv` to the recorder, like this
```yaml
ffmpeg:
  camera:
    BackEast:
       name: Back_East
       host: !secret camera_ip_back_east
       username: !secret camera_us_back_east
       password: !secret camera_pw_back_east
       path: /cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif/trackID=0
       port: 554
       fps: 29
       recorder:
         idle_timeout: 1
         extension: mkv
         filename_pattern: 'BackE_%Y-%m-%d-%H%M%S'
         lookback: 12
         retain: 90
         thumbnail:
           filename_pattern: 'BackE_%Y-%m-%d-%H%M%S'

darknet:
  object_detector:
    model_path: /detectors/models/darknet/yolov4-csp-x-swish.weights
    model_config: /detectors/models/darknet/yolov4-csp-x-swish.cfg
    cameras:
      BackEast:
        fps: 2
        labels:
          - label: person
            confidence: 0.9
            trigger_recorder: true
          - label: dog
            trigger_recorder: true
          - label: cat
            trigger_recorder: true
background_subtractor:
  motion_detector:
    cameras:
      BackEast:
        fps: 2
        mask:
          - coordinates:
              - x: 1914
                y: 1
              - x: 320
                y: 1
              - x: 320
                y: 148
              - x: 872
                y: 33
              - x: 1914
                y: 174


nvr:
  BackEast:

webserver:

mqtt:
  broker: !secret mqtt_host
  port: !secret mqtt_port
  username: !secret mqtt_us
  password: !secret mqtt_pw
  client_id: viseron
  home_assistant:

logger:
  default_level: debug
  logs:
    viseron.components.data_stream: info
    viseron.components.background_subtractor: info
    viseron.components.mog2: info
```
