### ISSUE TITLE
Modularized :: On an Error, camera username and password revealed

### ISSUE THREAD

**Issue by gniknalu** [roflcoopter/viseron#334]
In previous versions the camera username and password were masked. In the modularized version they're not. Is this done on purpose or is this a bug?

Thank you

**Comment by roflcoopter** [comment]
Definitely a bug! What log message are you referring to?

**Comment by roflcoopter** [comment]
I think i found where this was happening.
They were shown in the logs through an exception thrown on errors from FFprobe, which bypasses my filter that redacts the information.

I will remove the ffprobe command from the exception and log it instead, where it will be properly redacted

**Comment by gniknalu** [comment]
> I think i found where this was happening. They were shown in the logs through an exception thrown on errors from FFprobe, which bypasses my filter that redacts the information.

Here is a redacted sample:

```
[2022-03-11 12:11:29] [INFO    ] [viseron                 ] - -------------------------------------------
[2022-03-11 12:11:29] [INFO    ] [viseron                 ] - Initializing...
[2022-03-11 12:11:29] [INFO    ] [viseron.components      ] - Setting up logger
[2022-03-11 12:11:29] [INFO    ] [viseron.components      ] - Setting up data_stream
[2022-03-11 12:11:29] [INFO    ] [viseron.components      ] - Setting up ffmpeg
[2022-03-11 12:11:29] [INFO    ] [viseron.components      ] - Setting up background_subtractor
[2022-03-11 12:11:29] [INFO    ] [viseron.components      ] - Setting up mqtt
[2022-03-11 12:11:29] [INFO    ] [viseron.components      ] - Setting up deepstack
[2022-03-11 12:11:29] [INFO    ] [viseron.components      ] - Setting up webserver
[2022-03-11 12:11:30] [INFO    ] [viseron.components      ] - Setting up domain camera for component ffmpeg, message repeated 3 times
[2022-03-11 12:11:30] [INFO    ] [viseron.components      ] - Setting up domain motion_detector for component background_subtractor
[2022-03-11 12:11:30] [INFO    ] [viseron.components      ] - Setting up domain object_detector for component deepstack
[2022-03-11 12:11:45] [ERROR   ] [viseron.components.ffmpeg.stream.BackEast] - Retrying None in 2.0 seconds as it raised FFprobeTimeout: FFprobe command ffprobe -hide_banner -loglevel error -print_format json -show_error -show_streams rtsp://xxxxxxxxx:xxxxxxxxx@xxx.xxx.xxx.xxx:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif/trackID=0 timed out after 15s.
[2022-03-11 12:12:00] [ERROR   ] [viseron.components      ] - ffmpeg_setup_camera did not finish in time
[2022-03-11 12:12:00] [ERROR   ] [viseron.components      ] - background_subtractor_setup_motion_detector did not finish in time
[2022-03-11 12:12:00] [ERROR   ] [viseron.components      ] - deepstack_setup_object_detector did not finish in time
[2022-03-11 12:12:00] [INFO    ] [viseron.components      ] - Setting up nvr
Traceback (most recent call last):
  File "/src/viseron/components/nvr/__init__.py", line 95, in setup
    nvr = NVR(vis, validated_config, camera_identifier)
  File "/src/viseron/components/nvr/__init__.py", line 172, in __init__
    self._camera: AbstractCamera = vis.get_registered_camera(camera_identifier)
  File "/src/viseron/__init__.py", line 272, in get_registered_camera
    raise CameraNotRegisteredError(
viseron.exceptions.CameraNotRegisteredError: Requested camera BackEast has not been registered. Available cameras are: FrontEast2, FrontWest
[2022-03-11 12:12:00] [ERROR   ] [viseron.components.nvr  ] - Uncaught exception setting up nvr for camera BackEast: Requested camera BackEast has not been registered. Available cameras are: FrontEast2, FrontWest
None
[2022-03-11 12:12:00] [INFO    ] [viseron                 ] - Initialization complete
[2022-03-11 12:12:17] [ERROR   ] [viseron.components.ffmpeg.stream.BackEast] - Retrying None in 4.0 seconds as it raised FFprobeTimeout: FFprobe command ffprobe -hide_banner -loglevel error -print_format json -show_error -show_streams rtsp://xxxxxxxxx:xxxxxxxxx@xxx.xxx.xxx.xxx:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif/trackID=0 timed out after 30s.

```

**Comment by gniknalu** [comment]
I couldn't fine any more in my logs after downloading the latest container. Thank you!
