### ISSUE TITLE
Modularize - ffmpeg crashing

### ISSUE THREAD

**Issue by bailboy91** [roflcoopter/viseron#352]
At seemingly random times ffmpeg is killed and does not recover.  Currently only using a single camera with rtsp.  When checking nvtop the ffmpeg service is not running while the viseron services are still running.  I've been testing different config options to get faster object detection and not sure if this is a side effect. 

Error from debug:
```
[2022-06-01 08:44:56] [DEBUG   ] [viseron.components.ffmpeg.stream.viseron-front] - frame=  322 fps=9.8 q=-1.0 q=-0.0 size=N/A time=00:00:35.14 bitrate=N/A speed=1.06x
[2022-06-01 08:44:57] [DEBUG   ] [viseron.components.ffmpeg.stream.viseron-front] - frame=  328 fps=9.8 q=-1.0 q=-0.0 size=N/A time=00:00:35.74 bitrate=N/A speed=1.06x
[2022-06-01 08:44:57] [DEBUG   ] [viseron.components.ffmpeg.stream.viseron-front] - frame=  333 fps=9.8 q=-1.0 q=-0.0 size=N/A time=00:00:36.24 bitrate=N/A speed=1.06x
[2022-06-01 08:44:58] [DEBUG   ] [viseron.components.ffmpeg.stream.viseron-front] - frame=  339 fps=9.8 q=-1.0 q=-0.0 size=N/A time=00:00:36.84 bitrate=N/A speed=1.06x
[2022-06-01 08:44:58] [DEBUG   ] [viseron.components.ffmpeg.stream.viseron-front] - frame=  345 fps=9.8 q=-1.0 q=-0.0 size=N/A time=00:00:37.44 bitrate=N/A speed=1.06x
[2022-06-01 08:44:59] [DEBUG   ] [viseron.components.ffmpeg.stream.viseron-front] - frame=  350 fps=9.8 q=-1.0 q=-0.0 size=N/A time=00:00:37.94 bitrate=N/A speed=1.06x
[2022-06-01 08:44:59] [DEBUG   ] [viseron.components.ffmpeg.stream.viseron-front] - frame=  355 fps=9.8 q=-1.0 q=-0.0 size=N/A time=00:00:38.44 bitrate=N/A speed=1.06x
[2022-06-01 08:45:00] [DEBUG   ] [viseron.components.ffmpeg.stream.viseron-front] - frame=  361 fps=9.8 q=-1.0 q=-0.0 size=N/A time=00:00:39.05 bitrate=N/A speed=1.06x
[2022-06-01 08:45:10] [DEBUG   ] [viseron.components.ffmpeg.stream.viseron-front] - frame=  367 fps=9.8 q=-1.0 q=-0.0 size=N/A time=00:00:39.65 bitrate=N/A speed=1.06x
[2022-06-01 08:45:12] [DEBUG   ] [viseron.watchdog.thread_watchdog] - Thread viseron.camera.viseron-front is stuck
[2022-06-01 08:45:19] [DEBUG   ] [viseron.components.ffmpeg.stream.viseron-front] - frame=  370 fps=8.6 q=-1.0 q=-0.0 size=N/A time=00:00:39.95 bitrate=N/A speed=0.931x
[2022-06-01 08:45:19] [DEBUG   ] [viseron.components.ffmpeg.stream.viseron-front] - [segment @ 0x55575f5a7c80] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[2022-06-01 08:45:19] [DEBUG   ] [viseron.components.ffmpeg.stream.viseron-front] - [segment @ 0x55575f5a7c80] segment:'/segments/viseron-front/20220601084455.mp4' count:7 ended
[2022-06-01 08:45:19] [DEBUG   ] [viseron.components.ffmpeg.stream.viseron-front] - [AVIOContext @ 0x55575f751f40] Statistics: 2 seeks, 6 writeouts
[2022-06-01 08:45:19] [DEBUG   ] [viseron.components.ffmpeg.stream.viseron-front] - [segment @ 0x55575f5a7c80] Opening '/segments/viseron-front/20220601084519.mp4' for writing
[2022-06-01 08:45:19] [DEBUG   ] [viseron.components.ffmpeg.stream.viseron-front] - [segment @ 0x55575f5a7c80] segment:'/segments/viseron-front/20220601084519.mp4' starts with packet stream:0 pts:412209 pts_time:40.2548 frame:370
[2022-06-01 08:45:19] [DEBUG   ] [viseron.states] - Setting state of binary_sensor.viseron_front_connected to state: off, attributes {}
[2022-06-01 08:45:20] [DEBUG   ] [viseron.states] - Setting state of sensor.viseron_front_object_detector_fps to state: 0, attributes {'preprocessor_fps': 0, 'inference_fps': 0, 'theoretical_max_fps': 0}
[2022-06-01 08:45:24] [DEBUG   ] [viseron.components.ffmpeg.stream.viseron-front] - FFmpeg did not terminate, killing instead.
[2022-06-01 08:45:24] [DEBUG   ] [viseron.components.ffmpeg.camera.viseron-front] - FFmpeg frame reader stopped
[2022-06-01 08:45:24] [DEBUG   ] [viseron.watchdog.thread_watchdog] - Thread viseron.camera.viseron-front is dead, restarting
[2022-06-01 08:45:24] [DEBUG   ] [viseron.states] - Setting state of toggle.viseron_front_connection to state: off, attributes {}
[2022-06-01 08:45:24] [ERROR   ] [apscheduler.executors.default] - Job "ThreadWatchDog.watchdog (trigger: interval[0:00:15], next run at: 2022-06-01 12:45:27 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/src/viseron/watchdog/thread_watchdog.py", line 180, in watchdog
    self.registered_items[index] = registered_thread.clone()
IndexError: list assignment index out of range
[2022-06-01 08:45:25] [DEBUG   ] [viseron.states] - Setting state of sensor.viseron_front_operation_state to state: idle, attributes {}
[2022-06-01 09:04:20] [DEBUG   ] [viseron.states] - Setting state of sensor.viseron_front_object_detector_fps to state: 0, attributes {'preprocessor_fps': 0, 'inference_fps': 0, 'theoretical_max_fps': 0}, message repeated 38 times
```

Config.yml:
```
ffmpeg: # <-- component
  camera: # <-- domain
    viseron-front: # <-- camera identifier
       name: viseron-front
       host: 192.168.1.163
       path: /video3_unicast
       port: 8554
       username:
       password:
       fps: 10
       width: 1280
       height: 720
       stream_format: rtsp
       frame_timeout: 10
       ffmpeg_loglevel: verbose
       recorder:
         codec: h264
         lookback: 5
         retain: 7
       mjpeg_streams:
         front_stream:
           draw_objects: true

#mog2:
background_subtractor:
  motion_detector:
    cameras:
      viseron-front:
        fps: 4
#        width: 852
#        height: 480
        trigger_recorder: false
#        area: 0.1
#        learning_rate: 0.1
        threshold: 4
        alpha: 0.4
#        mask:
#          - coordinates:
#              - x: 346
#                y: 201
#              - x: 856
#                y: 233
#              - x: 1162
#                y: 590
#              - x: 430
#                y: 631
#              - x: 285
#                y: 458

darknet:
  object_detector:
#    model_path: /config/yolov4x-mish.weights
#    model_config: /config/yolov4x-mish.cfg
    model_path: /detectors/models/darknet/yolov4-csp-x-swish.weights
    model_config: /detectors/models/darknet/yolov4-csp-x-swish.cfg
    label_path: /detectors/models/darknet/coco.names
    suppression: 0.4
    cameras:
      viseron-front:
        fps: 4
        scan_on_motion_only: true
        labels:
          - label: person
            confidence: 0.6
            trigger_recorder: true

nvr:
  viseron-front:

mqtt:
  broker: xxxxxxxxx
  username: xxxxxxxxxx
  password: "xxxxxxxxxxx"
  home_assistant:
  client_id: viseron

logger:
  default_level: debug
  logs:
    viseron.components.data_stream: info
    viseron.components.background_subtractor: info
    viseron.components.mog2: info
```

**Comment by roflcoopter** [comment]
Thanks for the report!
Found the bug thats causing the crash, will fix soon.

However it looks like Viseron isnt receiving a frame within the `frame_timeout` window.
Is your camera connection stable if you view it from, for example a VLC client?

**Comment by bailboy91** [comment]
Incredible you found the bug so fast! Thank you!  

As for the frame time out that's another issue I've been trying to figure out.  VLC or motioneye do not drop the stream or have an complaints that i can tell.  The feed is from a custom flashed Wyzecam V2 that I've messed with the v4l2rtspserver stream and i think that's the real issue.  When i had default settings viseron didn't notice any dropped frames or experience frame_timeout issues.

**Comment by roflcoopter** [comment]
It was a bit trickier than i had anticipated, wont have time for it today.
Will try to get it done during the weekend.



> As for the frame time out that's another issue I've been trying to figure out. VLC or motioneye do not drop the stream or have an complaints that i can tell. The feed is from a custom flashed Wyzecam V2 that I've messed with the v4l2rtspserver stream and i think that's the real issue. When i had default settings viseron didn't notice any dropped frames or experience frame_timeout issues.

That is odd indeed, so its working fine if you run your object/motion detector at 1 FPS, but not when you run at 4 FPS?

**Comment by bailboy91** [comment]
> That is odd indeed, so its working fine if you run your object/motion detector at 1 FPS, but not when you run at 4 FPS?
Let me test this really quick before I commit to an answer lol.  I think overall i had better detection at 4fps over 1 but we'll see if that's tied to the issue at hand.

**Comment by bailboy91** [comment]
Ah okay, same exact behavior 1 vs 4 fps.

**Comment by bailboy91** [comment]
Well, ok.  Doing some additional testing.  With the FPS of the camera set to 25 (fps rtsp is sending)  and then timeout set to 30 I have yet to have ffmpeg crash.

**Comment by roflcoopter** [comment]
I pushed some improvements now to the `modularized` tag.

Sorry it took so long!
When i fixed this bug i encountered a few more that i had to squash.

Recovery in-case of crashes in any threads is now mor robust

**Comment by bailboy91** [comment]
Sorry for my delayed response too!  I am closing this as performance has had quite the uplift and I am no longer seeing crashes take it all down. everything is recovering! Thank you so much!
