### ISSUE TITLE
OpenCV libs "missing"

### ISSUE THREAD

**Issue by bailboy91** [roflcoopter/viseron#443]
On the latest dev branch docker.  Darknet will not start due to missing libopencv_*.so.405

These ARE missing it appears but that is because version 406 is in place.  I have been attempting to soft link them but there's so many.  

Below is my error. I can attach my config if you believe it to be useful! I am using yolov7-tiny and tried yolov4-tiny as well with same error. I don't think those have anything to do with the library woes. 
```
[2022-12-26 19:17:28] [DEBUG   ] [viseron.components.darknet] - Using native Darknet
[2022-12-26 19:17:28] [DEBUG   ] [viseron.components.darknet] - Using weights /detectors/models/darknet/yolov7-tiny.weights and config /detectors/models/darknet/yolov7-tiny.cfg, 416x416
[2022-12-26 19:17:28] [DEBUG   ] [viseron.components.darknet] - Creating Darknet data file /root/darknet_data.data
Traceback (most recent call last):
  File "/src/viseron/components/__init__.py", line 130, in setup_component
    result = component_module.setup(self._vis, config)
  File "/src/viseron/components/darknet/__init__.py", line 123, in setup
    vis.data[COMPONENT] = DarknetNative(vis, config[CONFIG_OBJECT_DETECTOR])
  File "/src/viseron/components/darknet/__init__.py", line 318, in __init__
    self._darknet = darknet.DarknetWrapper(config[CONFIG_HALF_PRECISION])
  File "/src/viseron/components/darknet/darknet.py", line 68, in __init__
    self._lib = CDLL(library, RTLD_GLOBAL)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libopencv_imgproc.so.405: cannot open shared object file: No such file or directory
[2022-12-26 19:17:28] [ERROR   ] [viseron.components] - Uncaught exception setting up component darknet: libopencv_imgproc.so.405: cannot open shared object file: No such file or directory
None
[2022-12-26 19:17:28] [ERROR   ] [viseron.components] - Setup of component darknet failed
[2022-12-26 19:17:28] [ERROR   ] [viseron.components] - Failed setup of component darknet
```

**Comment by bailboy91** [comment]
update already,  I used `:latest` in docker compose file and it's working just fine. Just the dev branch is experiencing the above issue.

**Comment by roflcoopter** [comment]
Thanks for the report! Which container is this, the Nano one?

**Comment by bailboy91** [comment]
Oh so sorry! Meant to include that. I am using 'amd64-cuda-viseron:dev'

**Comment by roflcoopter** [comment]
The builds are fixed now! Working on my end, please try it out when you get the time

**Comment by bailboy91** [comment]
Looks great! Darknet loads and i can see it in nvtop! I'll sit on this for a day or so and then close it out! Thank you for your work!

**Comment by bailboy91** [comment]
It is working perfectly on the latest dev. Closing this out.
