### ISSUE TITLE
Uncaught thread exception

### ISSUE THREAD

**Issue by netpro25** [roflcoopter/viseron#496]
I was wanting to be able to view the camera on HomeAsistant to then be able to see it on my Echo Show, however after setting up substreams and mjpeg streams I'm now (randomly) seeing this error in the logs. Do you need anymore information for troubleshooting? Is my config off?

```
[2023-03-03 12:40:07] [ERROR   ] [root] - Uncaught thread exception
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/src/viseron/components/data_stream/__init__.py", line 185, in consume_data
    self.static_subscriptions(data_item)
  File "/src/viseron/components/data_stream/__init__.py", line 165, in static_subscriptions
    self.run_callbacks(
  File "/src/viseron/components/data_stream/__init__.py", line 122, in run_callbacks
    for callback in callbacks.values():
RuntimeError: dictionary changed size during iteration
[2023-03-03 12:40:15] [ERROR   ] [viseron.watchdog.thread_watchdog] - Thread data_stream is dead, restarting
```

Here's my config

```yaml
ffmpeg:
  camera:
    camera_1:  # This value has to be unique across all cameras
      name: Drive
      host: 192.168.0.204
      port: 554
      path: /cam/realmonitor?channel=1&subtype=0
      recorder:
        idle_timeout: 30
        codec: h264
      username: admin
      password: redacted
      substream:
        path: /cam/realmonitor?channel=1&subtype=1
        port: 554
      mjpeg_streams:
        camera1stream:
          draw_objects: true
          draw_zones: false
          draw_object_mask: false

darknet:
  object_detector:
    cameras:
      camera_1:  # Attach detector to the configured camera_1 above
        fps: 1
        scan_on_motion_only: false  # Scan for objects even when there is no motion
        labels:
          - label: dog
            confidence: 0.7
            trigger_recorder: false
          - label: person
            confidence: 0.75
            trigger_recorder: true
          - label: car
            confidence: .7
            trigger_recorder: true
            require_motion: true
          - label: truck
            confidence: .7
            trigger_recorder: true
            require_motion: true            

mog2:
  motion_detector:
    cameras:
      camera_1:
        fps: 1

nvr:
  camera_1:  # Run NVR for camera_1

mqtt:
  broker: mosquitto
  port: 1883
  username: homeassistant
  password: redacted
  home_assistant:

```

**Comment by netpro25** [comment]
This error has gone away since I've made more modifications to my config. I've also removed the mjpeg streams as they didn't work how I wanted.
