### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn' in jetson-nano-viseron docker image

### ISSUE THREAD

**Issue by lukedoomer** [roflcoopter/viseron#530]
enable dlib in configuration causes error

```
2023-03-24 17:04:06] [INFO    ] [viseron.components] - Setting up domain face_recognition for component dlib with identifier luke_garage
[2023-03-24 17:04:18] [ERROR   ] [root] - Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/src/viseron/__main__.py", line 33, in <module>
    sys.exit(init())
  File "/src/viseron/__main__.py", line 29, in init
    return main()
  File "/src/viseron/__main__.py", line 20, in main
    viseron = setup_viseron()
  File "/src/viseron/__init__.py", line 149, in setup_viseron
    setup_domains(vis)
  File "/src/viseron/components/__init__.py", line 597, in setup_domains
    future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/src/viseron/components/__init__.py", line 351, in setup_domain
    domain_module = self.get_domain(domain_to_setup.domain)
  File "/src/viseron/components/__init__.py", line 212, in get_domain
    return importlib.import_module(f"{self._path}.{domain}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/src/viseron/components/dlib/face_recognition.py", line 17, in <module>
    from .train import train
  File "/src/viseron/components/dlib/train.py", line 9, in <module>
    from sklearn import neighbors
ModuleNotFoundError: No module named 'sklearn'
```

**Comment by roflcoopter** [comment]
Thanks for the report!

What Docker tag are you using, is it the `dev` tag?

**Comment by lukedoomer** [comment]
I am using `latest` image. Should I use `dev` tag?

**Comment by lukedoomer** [comment]
> I have made some changes to the way dlib (and sklearn) is installed, which I think would fix this problem.
> 
> Could you give `dev` a go and see if it helps?

`dev` seems working well because no more ModuleNotFoundError.

And one more question, Is dlib the only GPU/CUDA accelerated face recognition?
Considering the computing resource of jetson nano, users of jetson nano should choose dlib as face recognition component,  right?

**Comment by roflcoopter** [comment]
Great!

[CompreFace](https://viseron.netlify.app/components-explorer/components/compreface) has support for the Nano as well, i would suggest using that since its way more accurate and optimized than `dlib`
