### ISSUE TITLE
I got an error when running YoloV4 in anaconda

### ISSUE THREAD

**Issue by dasss** [roflcoopter/viseron#535]
Traceback (most recent call last):
  File "detect_video.py", line 178, in <module>
    app.run(main)
  File "C:\Users\danie\anaconda3\envs\yolov4-cpu\lib\site-packages\absl\app.py", line 308, in run
    _run_main(main, args)
  File "C:\Users\danie\anaconda3\envs\yolov4-cpu\lib\site-packages\absl\app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "detect_video.py", line 160, in main
    image = utils.draw_bbox(frame, pred_bbox, FLAGS.info, allowed_classes=allowed_classes, read_plate=FLAGS.plate)
  File "D:\YoloV4\yolov4-custom-functions\core\utils.py", line 249, in draw_bbox
    cv2.rectangle(image, c1, c2, bbox_color, bbox_thick)
cv2.error: OpenCV(4.6.0) :-1: error: (-5:Bad argument) in function 'rectangle'
> Overload resolution failed:
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
>  - Can't parse 'rec'. Expected sequence length 4, got 2
>  - Can't parse 'rec'. Expected sequence length 4, got 2

**Comment by roflcoopter** [comment]
Viseron is sadly not officially supported on Windows

**Comment by dasss** [comment]
@roflcoopter 
Okay thanks
