### ISSUE TITLE
Darknet Component

### ISSUE THREAD

**Issue by Dvalin21** [roflcoopter/viseron#552]
When trying to setup Darknet, i get the following

Traceback (most recent call last):
  File "/src/viseron/components/__init__.py", line 130, in setup_component
    result = component_module.setup(self._vis, config)
  File "/src/viseron/components/darknet/__init__.py", line 125, in setup
    vis.data[COMPONENT] = DarknetDNN(vis, config[CONFIG_OBJECT_DETECTOR])
  File "/src/viseron/components/darknet/__init__.py", line 219, in __init__
    super().__init__(vis, config)
  File "/src/viseron/components/darknet/__init__.py", line 164, in __init__
    self._model_width = int(model_config.get("net", "width"))
  File "/usr/lib/python3.8/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.8/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'net'
[2023-04-21 22:41:42] [ERROR   ] [viseron.components] - Uncaught exception setting up component darknet: No section: 'net'
None
[2023-04-21 22:41:42] [ERROR   ] [viseron.components] - Setup of component darknet failed
[2023-04-21 22:41:42] [ERROR   ] [viseron.components] - Failed setup of component darknet

**Comment by roflcoopter** [comment]
Seems similar to #476 

What hardware are you running on?

**Comment by Dvalin21** [comment]
> Seems similar to #476
> 
> What hardware are you running on?

OS: Ubuntu 22.04.2 LTS x86_64/Installed on top CasaOS
Host: B550 AORUS ELITE AX 
Kernel: 5.15.0-70-generic 
Uptime: 10 hours, 58 mins 
Packages: 1157 (dpkg), 6 (snap) 
Shell: bash 5.1.16 
CPU: AMD Ryzen 5 3600 (12) @ 3.600GHz 
GPU: AMD ATI Radeon RX 5500/5500M / Pro 5500M 
Memory: 9943MiB / 64211MiB
Also the M.2 Coral

**Comment by Dvalin21** [comment]
@roflcoopter Not sure what it was, but the error didn't come back after the update. Ill use logs debug just in case and bring logs. Thanks!

**Comment by Dvalin21** [comment]
@roflcoopter So after the update, absolutely no errors, however I have it set for recording trigger on darknet when object is detected. However, since then I have not been able to get record trigger to happen on detection.
