### ISSUE TITLE
Rpi4: problem at run docker image

### ISSUE THREAD

**Issue by dadaloop82** [roflcoopter/viseron#66]
Hi everyone, I have a Pi4 with GPU memory up to 320Mb, I tried to make the docker image work but unfortunately it fails me at initialization.
Where am I going wrong?
Thank you very much

**Command:**
`docker run --rm \
--privileged \
-v /home/pi/docker/viseron/recording:/recordings \
-v /home/pi/docker/viseron/config:/config \
-v /etc/localtime:/etc/localtime:ro \
-v /dev/bus/usb:/dev/bus/usb \
-v /opt/vc/lib:/opt/vc/lib \
--name viseron \
--device /dev/vchiq:/dev/vchiq --device /dev/vcsm:/dev/vcsm \
roflcoopter/viseron-rpi:latest`

**Result**
`Traceback (most recent call last):
  File "viseron.py", line 8, in <module>
    from lib.config import ViseronConfig, NVRConfig, CONFIG
  File "/src/viseron/lib/config/__init__.py", line 101, in <module>
    CONFIG = VISERON_CONFIG_SCHEMA(raw_config)
  File "/usr/local/lib/python3.7/dist-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/dist-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/dist-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: expected a dictionary for dictionary value @ data['object_detection']['logging']
`

**Comment by dadaloop82** [comment]
I had to explicitly configure the following parameters for the camera, it does not automatically take them from the stream:

cameras:
   width: 1920
    height: 1080
    stream_format: rtsp
    fps: 10
    codec: h264

Now perform the initialization but I have another error:

_Error starting decoder pipe! ffmpeg: error while loading shared libraries: libmmal_core.so: cannot open shared object file: No such file or directory_


I will try to investigate and send updates.

**Comment by dadaloop82** [comment]
**UPDATE**

So, the file "libmmal_core.so", in my host system, is in the folder "/opt/vc/lib/".
From the docker's startup file there is the reference

```
...
-v /opt/vc/lib:/opt/vc/lib \
...
```

So in theory it should take to the correct host folder and map it in the docker, but obviously it can't do it. The file is always untraceable.

I ask for help :)

**Comment by roflcoopter** [comment]
There is another issue open for RPi4 support #1. Would appreciate if you could report your findings there instead

The rpi image is built on a RPi3 B+ so i suspect this might have something to do with it. I cant be of much help im afraid since i dont have an RPi4 to test with.

Can you enable debug logging and post the full log? Along with your config.yaml
What you could try is to build the image yourself locally and see if that works.

**Comment by dadaloop82** [comment]
Thank you for your answer., @roflcoopter !

== config ==
cameras:
  - name: soggiorno
    mqtt_name: viseron_soggiorno    
    host: 192.168.1.14
    port: 554
    username: [username]
    password: [password]
    path: /Streaming/Channels/101/    
    width: 800
    height: 600
    stream_format: rtsp
    fps: 6

== run with ==
`docker run --rm \
--privileged \
-v /home/pi/docker/viseron/recording:/recordings \
-v /home/pi/docker/viseron/config:/config \
-v /etc/localtime:/etc/localtime:ro \
-v /dev/bus/usb:/dev/bus/usb \
-v /opt/vc/lib:/opt/vc/lib \
--name viseron \
--device /dev/vchiq:/dev/vchiq --device /dev/vcsm:/dev/vcsm \
roflcoopter/viseron-rpi:latest`

== debug ==
`[2020-10-23 12:25:25] [root                    ] [INFO    ] - -------------------------------------------
[2020-10-23 12:25:25] [root                    ] [INFO    ] - Initializing...
[2020-10-23 12:25:25] [root                    ] [DEBUG   ] - Starting cleanup scheduler
[2020-10-23 12:25:26] [root                    ] [DEBUG   ] - Running initial cleanup
[2020-10-23 12:25:26] [lib.cleanup             ] [DEBUG   ] - Running cleanup
[2020-10-23 12:25:26] [lib.detector            ] [DEBUG   ] - Initializing object detector edgetpu
[2020-10-23 12:25:26] [lib.detectors.edgetpu   ] [WARNING ] - EdgeTPU not found. Detection will run on CPU
[2020-10-23 12:25:26] [lib.detector            ] [DEBUG   ] - Object detector initialized
[2020-10-23 12:25:26] [root                    ] [INFO    ] - Initializing NVR threads
[2020-10-23 12:25:26] [lib.nvr.soggiorno       ] [DEBUG   ] - Initializing NVR thread
[2020-10-23 12:25:26] [lib.camera.soggiorno    ] [DEBUG   ] - Initializing ffmpeg RTSP pipe
[2020-10-23 12:25:26] [lib.camera.soggiorno    ] [DEBUG   ] - Getting stream information for rtsp://admin:SXRXKI@192.168.1.14:554/Streaming/Channels/101/
Traceback (most recent call last):
  File "viseron.py", line 177, in <module>
    Viseron()
  File "viseron.py", line 69, in __init__
    mqtt_queue=mqtt_queue,
  File "/src/viseron/lib/nvr.py", line 153, in __init__
    self.camera = FFMPEGCamera(config, frame_buffer)
  File "/src/viseron/lib/camera.py", line 127, in __init__
    self.start_decoder()
  File "/src/viseron/lib/camera.py", line 149, in start_decoder
    ) = self.get_stream_information(self._config.camera.stream_url)
  File "/src/viseron/lib/camera.py", line 226, in get_stream_information
    width, height, fps, codec = self.ffprobe_stream_information(stream_url)
  File "/src/viseron/lib/camera.py", line 193, in ffprobe_stream_information
    stream_information = json.loads(output)["streams"][0]
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

**Comment by roflcoopter** [comment]
There is some other issue with your configuration. Based on that error in the log it appears that ffprobe cant access the stream.

Are you running 64-bit RPi4?

**Comment by dadaloop82** [comment]
Yes, i have a Pi4 with 64bit build of lady raspian

**Comment by dadaloop82** [comment]
**UPDATE**
For testing, i have run:

`ffmpeg -i rtsp://admin[pwd]@192.168.1.14:554/Streaming/Channels/101 -f image2 -vf fps=fps=1/120 img%03d.jpg`

And results are correct:

```
Input #0, rtsp, from 'rtsp://admin:[pwd]@192.168.1.14:554/Streaming/Channels/101':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1280x720, 25 tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

**Comment by roflcoopter** [comment]
That might be why, the rpi image is specifically built on RPi3 32-bit.

I need to totally remake my way of working with the dockerfiles to be able to support the RPi 4 better.
This is quite a large process tho and it will probably take some time before i can do that.

**Comment by roflcoopter** [comment]
@dadaloop82 I finally got my multiarch builds to work, i put up a test-version under roflcoopter/viseron-new:docker_revamp

Could you try and see if it works on your RPi4? Currently the generated ffmpeg command wont recognize its an RPi4 so the hwaccel args wont be added automatically

**Comment by roflcoopter** [comment]
Closing due to inactivity, feel free to reopen if the issue persists
