### ISSUE TITLE
OSError: [Errno 8] Exec format error: 'MP4Box'

### ISSUE THREAD

**Issue by eldadh** [roflcoopter/viseron#752]
Hey
I'm Trying to run version 3.0.0b4 on RP4 and Received the fallowing errors:

[2024-05-17 12:55:29] [DEBUG   ] [viseron.domains.camera.fragmenter.camera_1] - Checking for new segments to fragment
[2024-05-17 12:55:29] [DEBUG   ] [viseron.domains.camera.fragmenter.camera_1] - Processing 1715939721.mp4
[2024-05-17 12:55:29] [ERROR   ] [viseron.domains.camera.fragmenter.camera_1] - Failed to fragment 1715939721.mp4
Traceback (most recent call last):
  File "/src/viseron/domains/camera/fragmenter.py", line 192, in _create_fragmented_mp4
    if self._mp4box_command(mp4):
  File "/src/viseron/domains/camera/fragmenter.py", line 111, in _mp4box_command
    sp.run(  # type: ignore[call-overload]
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'MP4Box'

**Comment by roflcoopter** [comment]
Should be fixed in v3.0.0b5!
