### ISSUE TITLE
Camera password consisting of only numbers, not working?

### ISSUE THREAD

**Issue by Edvin-89** [roflcoopter/viseron#800]
Hello!
I am trying to set up an installation with some D-Link DCS-6100LH cameras.
These cameras have a default password based on numbers that cannot be changed. When I enter those numbers under password I get the error message "Error validating config for domain camera and component ffmpeg: expected str for dictionary value @ data['camera_1']['password']. Got None".

From the log file.
[2024-08-20 09:47:03] [INFO    ] [viseron.core] - -------------------------------------------
[2024-08-20 09:47:03] [INFO    ] [viseron.core] - Initializing Viseron
[2024-08-20 09:47:03] [INFO    ] [viseron.components] - Setting up component data_stream
[2024-08-20 09:47:03] [INFO    ] [viseron.components] - Setup of component data_stream took 0.0 seconds
[2024-08-20 09:47:03] [INFO    ] [viseron.components] - Setting up component webserver
[2024-08-20 09:47:03] [INFO    ] [viseron.components] - Setup of component webserver took 0.0 seconds
[2024-08-20 09:47:03] [INFO    ] [viseron.components] - Setting up component mog2
[2024-08-20 09:47:03] [INFO    ] [viseron.components] - Setting up component darknet
[2024-08-20 09:47:03] [INFO    ] [viseron.components] - Setting up component ffmpeg
[2024-08-20 09:47:03] [INFO    ] [viseron.components] - Setting up component nvr
[2024-08-20 09:47:03] [INFO    ] [viseron.components] - Setup of component nvr took 0.0 seconds
[2024-08-20 09:47:03] [INFO    ] [viseron.components] - Setup of component mog2 took 0.0 seconds
[2024-08-20 09:47:03] [INFO    ] [viseron.components] - Setup of component ffmpeg took 0.0 seconds
[2024-08-20 09:47:03] [INFO    ] [viseron.components] - Setup of component darknet took 0.1 seconds
[2024-08-20 09:47:04] [INFO    ] [viseron.components] - Setting up domain camera for component ffmpeg with identifier camera_1
[2024-08-20 09:47:04] [INFO    ] [viseron.components] - Setting up domain motion_detector for component mog2 with identifier camera_1
[2024-08-20 09:47:04] [INFO    ] [viseron.components] - Setting up domain object_detector for component darknet with identifier camera_1
[2024-08-20 09:47:04] [INFO    ] [viseron.components] - Setting up domain nvr for component nvr with identifier camera_1
[2024-08-20 09:47:04] [INFO    ] [viseron.components] - Setting up domain camera for component ffmpeg with identifier camera_2
[2024-08-20 09:47:04] [INFO    ] [viseron.components] - Setting up domain motion_detector for component mog2 with identifier camera_2
[2024-08-20 09:47:04] [INFO    ] [viseron.components] - Setting up domain object_detector for component darknet with identifier camera_2
[2024-08-20 09:47:04] [INFO    ] [viseron.components] - Setting up domain nvr for component nvr with identifier camera_2
[2024-08-20 09:47:04] [ERROR   ] [viseron.components] - Error validating config for domain camera and component ffmpeg: expected str for dictionary value @ data['camera_1']['password']. ***** None
Traceback (most recent call last):
  File "/src/viseron/components/__init__.py", line 253, in validate_domain_config
    return domain_module.CONFIG_SCHEMA(config), None
  File "/usr/local/lib/python3.8/dist-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/dist-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.8/dist-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: expected str for dictionary value @ data['camera_1']['password']
[2024-08-20 09:47:04] [ERROR   ] [viseron.components] - Error validating config for domain camera and component ffmpeg: expected str for dictionary value @ data['camera_2']['password']. ***** None
Traceback (most recent call last):
  File "/src/viseron/components/__init__.py", line 253, in validate_domain_config
    return domain_module.CONFIG_SCHEMA(config), None
  File "/usr/local/lib/python3.8/dist-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/dist-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.8/dist-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: expected str for dictionary value @ data['camera_2']['password']
[2024-08-20 09:47:04] [ERROR   ] [viseron.components] - Setup of domain camera for component ffmpeg with identifier camera_2 failed
[2024-08-20 09:47:04] [ERROR   ] [viseron.components] - Setup of domain camera for component ffmpeg with identifier camera_1 failed
[2024-08-20 09:47:04] [ERROR   ] [viseron.components] - Unable to setup dependencies for domain motion_detector for component mog2. Failed dependencies: ['domain: camera, identifier: camera_2']
[2024-08-20 09:47:04] [ERROR   ] [viseron.components] - Unable to setup dependencies for domain motion_detector for component mog2. Failed dependencies: ['domain: camera, identifier: camera_1']
[2024-08-20 09:47:04] [ERROR   ] [viseron.components] - Unable to setup dependencies for domain object_detector for component darknet. Failed dependencies: ['domain: camera, identifier: camera_2', 'domain: motion_detector, identifier: camera_2']
[2024-08-20 09:47:04] [ERROR   ] [viseron.components] - Unable to setup dependencies for domain object_detector for component darknet. Failed dependencies: ['domain: camera, identifier: camera_1', 'domain: motion_detector, identifier: camera_1']
[2024-08-20 09:47:04] [ERROR   ] [viseron.components] - Unable to setup dependencies for domain nvr for component nvr. Failed dependencies: ['domain: camera, identifier: camera_2', 'domain: motion_detector, identifier: camera_2', 'domain: object_detector, identifier: camera_2']
[2024-08-20 09:47:04] [ERROR   ] [viseron.components] - Unable to setup dependencies for domain nvr for component nvr. Failed dependencies: ['domain: camera, identifier: camera_1', 'domain: motion_detector, identifier: camera_1', 'domain: object_detector, identifier: camera_1']
[2024-08-20 09:47:04] [INFO    ] [viseron.core] - Viseron initialized in 0.8 seconds

END OF LINE

/Edvin

**Comment by Edvin-89** [comment]
> Ahh, silly me! You can solve that by quoting the password tho.
> 
> ```yaml
> password: "123456"
> ```

Thanks for the quick reply, it did the trick!
Now it seems to try to start up the cameras, but runs into new problems. Don't know if it's something I did wrong in the configuration or if it's the cameras though.

Log file...
[2024-08-20 11:06:44] [INFO    ] [viseron.core] - -------------------------------------------
[2024-08-20 11:06:44] [INFO    ] [viseron.core] - Initializing Viseron
[2024-08-20 11:06:44] [INFO    ] [viseron.components] - Setting up component data_stream
[2024-08-20 11:06:44] [INFO    ] [viseron.components] - Setup of component data_stream took 0.0 seconds
[2024-08-20 11:06:44] [INFO    ] [viseron.components] - Setting up component webserver
[2024-08-20 11:06:44] [INFO    ] [viseron.components] - Setup of component webserver took 0.0 seconds
[2024-08-20 11:06:44] [INFO    ] [viseron.components] - Setting up component nvr
[2024-08-20 11:06:44] [INFO    ] [viseron.components] - Setting up component mog2
[2024-08-20 11:06:44] [INFO    ] [viseron.components] - Setting up component darknet
[2024-08-20 11:06:44] [INFO    ] [viseron.components] - Setup of component nvr took 0.0 seconds
[2024-08-20 11:06:44] [INFO    ] [viseron.components] - Setting up component ffmpeg
[2024-08-20 11:06:44] [INFO    ] [viseron.components] - Setup of component mog2 took 0.0 seconds
[2024-08-20 11:06:44] [INFO    ] [viseron.components] - Setup of component ffmpeg took 0.0 seconds
[2024-08-20 11:06:44] [INFO    ] [viseron.components] - Setup of component darknet took 0.1 seconds
[2024-08-20 11:06:44] [INFO    ] [viseron.components] - Setting up domain camera for component ffmpeg with identifier camera_1
[2024-08-20 11:06:44] [INFO    ] [viseron.components] - Setting up domain motion_detector for component mog2 with identifier camera_1
[2024-08-20 11:06:44] [INFO    ] [viseron.components] - Setting up domain object_detector for component darknet with identifier camera_1
[2024-08-20 11:06:45] [INFO    ] [viseron.components] - Setting up domain nvr for component nvr with identifier camera_1
[2024-08-20 11:06:45] [INFO    ] [viseron.components] - Setting up domain camera for component ffmpeg with identifier camera_2
[2024-08-20 11:06:45] [INFO    ] [viseron.components] - Setting up domain motion_detector for component mog2 with identifier camera_2
[2024-08-20 11:06:45] [INFO    ] [viseron.components] - Setting up domain object_detector for component darknet with identifier camera_2
[2024-08-20 11:06:45] [INFO    ] [viseron.components] - Setting up domain nvr for component nvr with identifier camera_2
[2024-08-20 11:07:00] [ERROR   ] [viseron.components.ffmpeg.stream.camera_1] - Retrying None in 2.0 seconds as it raised FFprobeTimeout: FFprobe command timed out after 15s.
[2024-08-20 11:07:00] [ERROR   ] [viseron.components.ffmpeg.stream.camera_2] - Retrying None in 2.0 seconds as it raised FFprobeTimeout: FFprobe command timed out after 15s.
[2024-08-20 11:07:05] [WARNING ] [viseron.components] - Setup of domain camera for component ffmpeg with identifier camera_1 is taking longer than 20 seconds
[2024-08-20 11:07:05] [WARNING ] [viseron.components] - Setup of domain camera for component ffmpeg with identifier camera_2 is taking longer than 20 seconds
[2024-08-20 11:07:32] [ERROR   ] [viseron.components.ffmpeg.stream.camera_1] - Retrying None in 4.0 seconds as it raised FFprobeTimeout: FFprobe command timed out after 30s.
[2024-08-20 11:07:32] [ERROR   ] [viseron.components.ffmpeg.stream.camera_2] - Retrying None in 4.0 seconds as it raised FFprobeTimeout: FFprobe command timed out after 30s.
[2024-08-20 11:07:36] [ERROR   ] [viseron.components.ffmpeg.stream.camera_1] - [rtsp @ 0x562e5aff84c0] method OPTIONS failed: 453 Not Enough Bandwidth
[2024-08-20 11:07:36] [ERROR   ] [viseron.components.ffmpeg.stream.camera_1] - rtsp://*****:*****@192.168.1.76:554/live/profile.0/video: Server returned 4XX Client Error, but not one of 40{0,1,3,4}
[2024-08-20 11:07:36] [ERROR   ] [viseron.components] - Domain camera for component ffmpeg is not ready. Retrying in 10 seconds. Error: FFprobe could not connect to stream. Output: {'error': {'code': -1482175736, 'string': 'Server returned 4XX Client Error, but not one of 40{0,1,3,4}'}}
[2024-08-20 11:07:36] [ERROR   ] [viseron.components.ffmpeg.stream.camera_2] - [rtsp @ 0x55e3e02274c0] method OPTIONS failed: 453 Not Enough Bandwidth
[2024-08-20 11:07:36] [ERROR   ] [viseron.components.ffmpeg.stream.camera_2] - rtsp://*****:*****@192.168.1.56:554/live/profile.0/video: Server returned 4XX Client Error, but not one of 40{0,1,3,4}
[2024-08-20 11:07:36] [ERROR   ] [viseron.components] - Domain camera for component ffmpeg is not ready. Retrying in 10 seconds. Error: FFprobe could not connect to stream. Output: {'error': {'code': -1482175736, 'string': 'Server returned 4XX Client Error, but not one of 40{0,1,3,4}'}}

My config...

ffmpeg:
  camera:

    camera_1:  # This value has to be unique across all cameras
      name: Altanen
      host: 192.168.1.76
      port: 554
      path: /live/profile.0/video
      username: admin
      password: "password numbers"
      fps: 15

    camera_2:  # This value has to be unique across all cameras
      name: Baksidan
      host: 192.168.1.56
      port: 554
      path: /live/profile.0/video
      username: admin
      password: "password numbers"
      fps: 15


darknet:
  object_detector:
    cameras:

      camera_1:  # Attach detector to the configured camera_1 above
        fps: 5
        scan_on_motion_only: false  # Scan for objects even when there is no motion
        labels:
          - label: person
            confidence: 0.75
            trigger_recorder: true

      camera_2:  # Attach detector to the configured camera_2 above
        fps: 5
        labels:
          - label: person
            confidence: 0.75
            trigger_recorder: true


mog2:
  motion_detector:
    cameras:

      camera_1:
        fps: 5
      camera_2:  # Attach detector to the configured camera_2 above
        fps: 5


nvr:
  camera_1:  # Run NVR for camera_1
  camera_2:  # Run NVR for camera_2

**Comment by roflcoopter** [comment]
Do you have any other software connected to the camera? Seems it can't handle more connections.

I have a very similar D-Link camera (also with number password) and it can only handle one stream at a time

**Comment by Edvin-89** [comment]
> Do you have any other software connected to the camera? Seems it can't handle more connections.
> 
> I have a very similar D-Link camera (also with number password) and it can only handle one stream at a time

Not while I'm trying to get them into Viseron, because I know they can only handle one stream at a time.
I otherwise have them connected to motioneye/home assistant.
But I'll keep thinking and try a few more things as well.

I tried to read a bit about ffmpeg and read about some who had the same problem with error code (453 Not Enough Bandwidth) where it was discussed/suggested to remove the audio stream which you should be able to do in ffmpeg. 
Is it something that can be done via the Viseron configuration?

**Comment by roflcoopter** [comment]
Yes you can set `audio_codec: null` in the camera config(if you are running the beta it has to be put under `recorder`)

**Comment by Edvin-89** [comment]
> Yes you can set `audio_codec: null` in the camera config(if you are running the beta it has to be put under `recorder`)

Thanks, will play around a bit and test my way around and see if I can get it to work. Running v3.0.0b9

Since the original problem is solved, it might be wrong to continue here with my other problems. Perhaps it would be better if I create a discussion thread.
