### ISSUE TITLE
v3.0.0b12: psycopg2.InterfaceError: cursor already closed

### ISSUE THREAD

**Issue by hessijames79** [roflcoopter/viseron#842]
Having updated to b12 I am getting the following exception regularly:

```
[2024-11-28 12:31:14] [ERROR   ] [root] - Uncaught thread exception in thread tier_handler_cam_01_stellplatz
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/cursor.py", line 1105, in fetchone
    row = dbapi_cursor.fetchone()
psycopg2.InterfaceError: cursor already closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/src/viseron/components/storage/tier_handler.py", line 236, in _process_events
    self._on_created(event)
  File "/src/viseron/components/storage/tier_handler.py", line 285, in _on_created
    self.check_tier()
  File "/src/viseron/components/storage/tier_handler.py", line 196, in check_tier
    self._check_tier(self._storage.get_session)
  File "/src/viseron/components/storage/tier_handler.py", line 214, in _check_tier
    for file in file_ids:
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 527, in iterrows
    for raw_row in self._fetchiter_impl():
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/cursor.py", line 2126, in _fetchiter_impl
    row = fetchone(self, self.cursor)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/cursor.py", line 1110, in fetchone
    self.handle_exception(result, dbapi_cursor, e)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/cursor.py", line 1081, in handle_exception
    result.connection._handle_dbapi_exception(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 2353, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/cursor.py", line 1105, in fetchone
    row = dbapi_cursor.fetchone()
sqlalchemy.exc.InterfaceError: (psycopg2.InterfaceError) cursor already closed
(Background on this error at: https://sqlalche.me/e/20/rvf5)
[2024-11-28 12:31:24] [ERROR   ] [viseron.watchdog.thread_watchdog] - Thread tier_handler_cam_01_stellplatz is dead, restarting
```

```
ffmpeg:
  camera:
    cam_01_stellplatz:
    [...]
      recorder:
        idle_timeout: 60
        lookback: 15
        max_recording_time: 600
        create_event_clip: true
        storage:
          tiers:
            - path: /data
              events:
                max_age:
                  days: 14
              continuous:
                max_age:
                  days: 7

```
Please let me know if you need additional information.

Patrick

**Comment by roflcoopter** [comment]
Is this issue still occuring frequently?

Thinking if the clean up jobs introduced in b12 are causing issues

**Comment by hessijames79** [comment]
> Is this issue still occuring frequently?
Yes. 69 exceptions yesterday, 53 today.

**Comment by roflcoopter** [comment]
Is it the exact same stack trace or does some of them reference self._check_tier(self._storage.get_session) from other rows?
That method is overridden in subclasses, would be good to know if it only affects that particular method

**Comment by hessijames79** [comment]
> Is it the exact same stack trace or does some of them reference self._check_tier(self._storage.get_session) from other rows? That method is overridden in subclasses, would be good to know if it only affects that particular method

Sorry, took me some time to process the logs. I examined 69 exceptions in the last 24 hours and they are all identical.

**Comment by hessijames79** [comment]
Getting a new exception now:
```
[2024-12-12 16:13:10] [ERROR   ] [root] - Uncaught thread exception in thread tier_handler_cam_01_stellplatz
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/src/viseron/components/storage/tier_handler.py", line 247, in _process_events
    self._on_created(event)
  File "/src/viseron/components/storage/tier_handler.py", line 296, in _on_created
    self.check_tier()
  File "/src/viseron/components/storage/tier_handler.py", line 201, in check_tier
    self._check_tier(self._storage.get_session)
  File "/src/viseron/components/storage/tier_handler.py", line 220, in _check_tier
    files = [
  File "/src/viseron/components/storage/tier_handler.py", line 221, in <listcomp>
    {"path": file.path, "tier_path": file.tier_path} for file in batch
AttributeError: 'int' object has no attribute 'path'
```

**Comment by roflcoopter** [comment]
New build on the way that fixes the last exception.

However i am not sure it fixes the original problem.
Will keep digging for a solution.

https://dev.azure.com/jespernilsson93/Viseron%20Pipelines/_build/results?buildId=746&view=results

**Comment by hessijames79** [comment]
> However i am not sure it fixes the original problem. Will keep digging for a solution.

Unfortunately, you are probably right (although the new stracktrace differs):

```
[2024-12-12 19:11:15] [ERROR   ] [root] - Uncaught thread exception in thread tier_handler_cam_06_garage
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/cursor.py", line 1211, in _buffer_rows
    new_rows = dbapi_cursor.fetchmany(size)
psycopg2.InterfaceError: cursor already closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/src/viseron/components/storage/tier_handler.py", line 241, in _process_events
    self._on_created(event)
  File "/src/viseron/components/storage/tier_handler.py", line 290, in _on_created
    self.check_tier()
  File "/src/viseron/components/storage/tier_handler.py", line 201, in check_tier
    self._check_tier(self._storage.get_session)
  File "/src/viseron/components/storage/tier_handler.py", line 218, in _check_tier
    for file in file_ids.yield_per(100):
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 527, in iterrows
    for raw_row in self._fetchiter_impl():
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/cursor.py", line 2126, in _fetchiter_impl
    row = fetchone(self, self.cursor)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/cursor.py", line 1237, in fetchone
    self._buffer_rows(result, dbapi_cursor)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/cursor.py", line 1213, in _buffer_rows
    self.handle_exception(result, dbapi_cursor, e)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/cursor.py", line 1081, in handle_exception
    result.connection._handle_dbapi_exception(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 2353, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/cursor.py", line 1211, in _buffer_rows
    new_rows = dbapi_cursor.fetchmany(size)
sqlalchemy.exc.InterfaceError: (psycopg2.InterfaceError) cursor already closed
(Background on this error at: https://sqlalche.me/e/20/rvf5)
```

**Comment by roflcoopter** [comment]
You could try setting sqlalchemy logging to debug like this:

```
logger:
  logs:
    viseron.components.storage: debug
    sqlalchemy.engine: debug
```

**Comment by roflcoopter** [comment]
Made yet another attempt, builds should be done soon: https://dev.azure.com/jespernilsson93/Viseron%20Pipelines/_build/results?buildId=747&view=results

**Comment by hessijames79** [comment]
> Made yet another attempt, builds should be done soon: 

Looks good so far. None of the above exceptions for 12 hours.

**Comment by roflcoopter** [comment]
Great! Closing this, feel free to reopen if the issues comes up again
