### ISSUE TITLE
Error Sensor

### ISSUE THREAD

**Issue by Spartan9802** [roflcoopter/viseron#97]
Hello,

I'm trying to install Viseron on a server at home and I end up with an error I don't understand. Can you help me? Thank you very much.

```
Traceback (most recent call last):

  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()

  File "/src/viseron/lib/nvr.py", line 495, in run
    self.update_status_sensor()

  File "/src/viseron/lib/nvr.py", line 484, in update_status_sensor
    self._mqtt.status_state = status

  File "/src/viseron/lib/nvr.py", line 90, in status_state
    self.devices["sensor"].publish(state, attributes=self.status_attributes)

KeyError: 'sensor'
```

config.yml

```
cameras:
  - name: Test
    host: 192.168.0.20
    port: 554
    path: /user=admin&password=****&channel=1&stream=0.sdp
    width: 1920
    height: 1080
    stream_format: rtsp
    fps: 10
    logging:
        level: debug
```

**Comment by roflcoopter** [comment]
Sorry about this, i will post a fix shortly to avoid this problem.

**Comment by roflcoopter** [comment]
version 1.7.2 is now out and fixes this
